### ISSUE TITLE
Мій звіт про результати коміта

### ISSUE THREAD

**Issue by IhorSikaliuk** [IhorSikaliuk/MTDIP-Sikaliuk-MainProject#1]
Я створив обліковий запис на GitHub. Після чого створив свій перший репозиторій.
![1](https://user-images.githubusercontent.com/45804526/49847783-8e7c2a80-fdda-11e8-9400-7ac1dbed6aaf.PNG)
Потім я додав викладача як співавтора репозиторія.
![2](https://user-images.githubusercontent.com/45804526/49847803-9fc53700-fdda-11e8-8705-e039626d06c5.PNG)
Створив перший файл в корені репозиторію MTDIP-Sikaliuk.txt
![3](https://user-images.githubusercontent.com/45804526/49847810-a5228180-fdda-11e8-8385-3617a29b7eee.PNG)

**Comment by smoktii-igov** [comment]
Ок
